# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import agent_pb2 as agent__pb2


class AgentStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetDiskInfo = channel.unary_unary(
        '/Agent/GetDiskInfo',
        request_serializer=agent__pb2.Request.SerializeToString,
        response_deserializer=agent__pb2.Response.FromString,
        )
    self.WriteCephConf = channel.unary_unary(
        '/Agent/WriteCephConf',
        request_serializer=agent__pb2.Request.SerializeToString,
        response_deserializer=agent__pb2.Response.FromString,
        )
    self.InstallPackage = channel.unary_unary(
        '/Agent/InstallPackage',
        request_serializer=agent__pb2.Request.SerializeToString,
        response_deserializer=agent__pb2.Response.FromString,
        )
    self.StartService = channel.unary_unary(
        '/Agent/StartService',
        request_serializer=agent__pb2.Request.SerializeToString,
        response_deserializer=agent__pb2.Response.FromString,
        )


class AgentServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetDiskInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def WriteCephConf(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def InstallPackage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StartService(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AgentServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetDiskInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetDiskInfo,
          request_deserializer=agent__pb2.Request.FromString,
          response_serializer=agent__pb2.Response.SerializeToString,
      ),
      'WriteCephConf': grpc.unary_unary_rpc_method_handler(
          servicer.WriteCephConf,
          request_deserializer=agent__pb2.Request.FromString,
          response_serializer=agent__pb2.Response.SerializeToString,
      ),
      'InstallPackage': grpc.unary_unary_rpc_method_handler(
          servicer.InstallPackage,
          request_deserializer=agent__pb2.Request.FromString,
          response_serializer=agent__pb2.Response.SerializeToString,
      ),
      'StartService': grpc.unary_unary_rpc_method_handler(
          servicer.StartService,
          request_deserializer=agent__pb2.Request.FromString,
          response_serializer=agent__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Agent', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
