# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import stor_pb2 as stor__pb2


class ManagerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetCephConf = channel.unary_unary(
        '/Manager/GetCephConf',
        request_serializer=stor__pb2.StorageLocation.SerializeToString,
        response_deserializer=stor__pb2.CephConf.FromString,
        )
    self.AppendCephMonitor = channel.unary_unary(
        '/Manager/AppendCephMonitor',
        request_serializer=stor__pb2.Request.SerializeToString,
        response_deserializer=stor__pb2.Response.FromString,
        )
    self.VolumeGet = channel.unary_unary(
        '/Manager/VolumeGet',
        request_serializer=stor__pb2.IdRequest.SerializeToString,
        response_deserializer=stor__pb2.Volume.FromString,
        )
    self.VolumeUpdate = channel.unary_unary(
        '/Manager/VolumeUpdate',
        request_serializer=stor__pb2.Volume.SerializeToString,
        response_deserializer=stor__pb2.Volume.FromString,
        )
    self.VolumeDelete = channel.unary_unary(
        '/Manager/VolumeDelete',
        request_serializer=stor__pb2.Volume.SerializeToString,
        response_deserializer=stor__pb2.Volume.FromString,
        )
    self.VolumeList = channel.unary_stream(
        '/Manager/VolumeList',
        request_serializer=stor__pb2.ListRequest.SerializeToString,
        response_deserializer=stor__pb2.Volume.FromString,
        )


class ManagerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetCephConf(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AppendCephMonitor(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def VolumeGet(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def VolumeUpdate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def VolumeDelete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def VolumeList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ManagerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetCephConf': grpc.unary_unary_rpc_method_handler(
          servicer.GetCephConf,
          request_deserializer=stor__pb2.StorageLocation.FromString,
          response_serializer=stor__pb2.CephConf.SerializeToString,
      ),
      'AppendCephMonitor': grpc.unary_unary_rpc_method_handler(
          servicer.AppendCephMonitor,
          request_deserializer=stor__pb2.Request.FromString,
          response_serializer=stor__pb2.Response.SerializeToString,
      ),
      'VolumeGet': grpc.unary_unary_rpc_method_handler(
          servicer.VolumeGet,
          request_deserializer=stor__pb2.IdRequest.FromString,
          response_serializer=stor__pb2.Volume.SerializeToString,
      ),
      'VolumeUpdate': grpc.unary_unary_rpc_method_handler(
          servicer.VolumeUpdate,
          request_deserializer=stor__pb2.Volume.FromString,
          response_serializer=stor__pb2.Volume.SerializeToString,
      ),
      'VolumeDelete': grpc.unary_unary_rpc_method_handler(
          servicer.VolumeDelete,
          request_deserializer=stor__pb2.Volume.FromString,
          response_serializer=stor__pb2.Volume.SerializeToString,
      ),
      'VolumeList': grpc.unary_stream_rpc_method_handler(
          servicer.VolumeList,
          request_deserializer=stor__pb2.ListRequest.FromString,
          response_serializer=stor__pb2.Volume.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Manager', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class AgentStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetDiskInfo = channel.unary_unary(
        '/Agent/GetDiskInfo',
        request_serializer=stor__pb2.Request.SerializeToString,
        response_deserializer=stor__pb2.Response.FromString,
        )
    self.WriteCephConf = channel.unary_unary(
        '/Agent/WriteCephConf',
        request_serializer=stor__pb2.Request.SerializeToString,
        response_deserializer=stor__pb2.Response.FromString,
        )
    self.InstallPackage = channel.unary_unary(
        '/Agent/InstallPackage',
        request_serializer=stor__pb2.Request.SerializeToString,
        response_deserializer=stor__pb2.Response.FromString,
        )
    self.StartService = channel.unary_unary(
        '/Agent/StartService',
        request_serializer=stor__pb2.Request.SerializeToString,
        response_deserializer=stor__pb2.Response.FromString,
        )


class AgentServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetDiskInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def WriteCephConf(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def InstallPackage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StartService(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AgentServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetDiskInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetDiskInfo,
          request_deserializer=stor__pb2.Request.FromString,
          response_serializer=stor__pb2.Response.SerializeToString,
      ),
      'WriteCephConf': grpc.unary_unary_rpc_method_handler(
          servicer.WriteCephConf,
          request_deserializer=stor__pb2.Request.FromString,
          response_serializer=stor__pb2.Response.SerializeToString,
      ),
      'InstallPackage': grpc.unary_unary_rpc_method_handler(
          servicer.InstallPackage,
          request_deserializer=stor__pb2.Request.FromString,
          response_serializer=stor__pb2.Response.SerializeToString,
      ),
      'StartService': grpc.unary_unary_rpc_method_handler(
          servicer.StartService,
          request_deserializer=stor__pb2.Request.FromString,
          response_serializer=stor__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Agent', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
