# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scheduler.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='scheduler.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0fscheduler.proto\"\x17\n\x08SRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x1a\n\tSResponse\x12\r\n\x05value\x18\x01 \x01(\t\"#\n\x0fStorageLocation\x12\x10\n\x08location\x18\x01 \x01(\t\"-\n\x08\x43\x65phConf\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x10\n\x08location\x18\x02 \x01(\t2g\n\tScheduler\x12,\n\x0bGetCephConf\x12\x10.StorageLocation\x1a\t.CephConf\"\x00\x12,\n\x11\x41ppendCephMonitor\x12\t.SRequest\x1a\n.SResponse\"\x00\x62\x06proto3')
)




_SREQUEST = _descriptor.Descriptor(
  name='SRequest',
  full_name='SRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='SRequest.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=42,
)


_SRESPONSE = _descriptor.Descriptor(
  name='SResponse',
  full_name='SResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='SResponse.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=70,
)


_STORAGELOCATION = _descriptor.Descriptor(
  name='StorageLocation',
  full_name='StorageLocation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='location', full_name='StorageLocation.location', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=107,
)


_CEPHCONF = _descriptor.Descriptor(
  name='CephConf',
  full_name='CephConf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='CephConf.content', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location', full_name='CephConf.location', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=154,
)

DESCRIPTOR.message_types_by_name['SRequest'] = _SREQUEST
DESCRIPTOR.message_types_by_name['SResponse'] = _SRESPONSE
DESCRIPTOR.message_types_by_name['StorageLocation'] = _STORAGELOCATION
DESCRIPTOR.message_types_by_name['CephConf'] = _CEPHCONF
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SRequest = _reflection.GeneratedProtocolMessageType('SRequest', (_message.Message,), {
  'DESCRIPTOR' : _SREQUEST,
  '__module__' : 'scheduler_pb2'
  # @@protoc_insertion_point(class_scope:SRequest)
  })
_sym_db.RegisterMessage(SRequest)

SResponse = _reflection.GeneratedProtocolMessageType('SResponse', (_message.Message,), {
  'DESCRIPTOR' : _SRESPONSE,
  '__module__' : 'scheduler_pb2'
  # @@protoc_insertion_point(class_scope:SResponse)
  })
_sym_db.RegisterMessage(SResponse)

StorageLocation = _reflection.GeneratedProtocolMessageType('StorageLocation', (_message.Message,), {
  'DESCRIPTOR' : _STORAGELOCATION,
  '__module__' : 'scheduler_pb2'
  # @@protoc_insertion_point(class_scope:StorageLocation)
  })
_sym_db.RegisterMessage(StorageLocation)

CephConf = _reflection.GeneratedProtocolMessageType('CephConf', (_message.Message,), {
  'DESCRIPTOR' : _CEPHCONF,
  '__module__' : 'scheduler_pb2'
  # @@protoc_insertion_point(class_scope:CephConf)
  })
_sym_db.RegisterMessage(CephConf)



_SCHEDULER = _descriptor.ServiceDescriptor(
  name='Scheduler',
  full_name='Scheduler',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=156,
  serialized_end=259,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetCephConf',
    full_name='Scheduler.GetCephConf',
    index=0,
    containing_service=None,
    input_type=_STORAGELOCATION,
    output_type=_CEPHCONF,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AppendCephMonitor',
    full_name='Scheduler.AppendCephMonitor',
    index=1,
    containing_service=None,
    input_type=_SREQUEST,
    output_type=_SRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SCHEDULER)

DESCRIPTOR.services_by_name['Scheduler'] = _SCHEDULER

# @@protoc_insertion_point(module_scope)
